-- Generated by make defaults. Omit setup() to use these built-in defaults.
require("xue-picker").setup({
  defaults = {
    actions = {},
    filter = {
      cwd = false,
    },
    frecency = {
      half_life = 2592000,
      max_size = 10000,
      save_delay_ms = 1000,
    },
    git = {
      enabled = true,
      modified_bonus = false,
    },
    gutter = "▌",
    highlights = {
      XuePickerBorder = {
        default = true,
        link = "FzfLuaBorder",
      },
      XuePickerBufferAlternate = {
        default = true,
        link = "FzfLuaBufFlagAlt",
      },
      XuePickerBufferCurrent = {
        default = true,
        link = "FzfLuaBufFlagCur",
      },
      XuePickerBufferGutter = {
        default = true,
        fg = "bg",
      },
      XuePickerBufferHeader = {
        default = true,
        link = "FzfLuaFzfHeader",
      },
      XuePickerBufferLineNr = {
        default = true,
        link = "FzfLuaPathLineNr",
      },
      XuePickerBufferMarker = {
        default = true,
        link = "FzfLuaFzfMarker",
      },
      XuePickerBufferMatch = {
        default = true,
        link = "FzfLuaFzfMatch",
      },
      XuePickerBufferNumber = {
        default = true,
        link = "FzfLuaBufNr",
      },
      XuePickerBufferPointer = {
        default = true,
        link = "FzfLuaFzfPointer",
      },
      XuePickerBufferSelected = {
        default = true,
        link = "FzfLuaFzfCursorLine",
      },
      XuePickerBufferStrong = {
        bold = true,
        default = true,
      },
      XuePickerColNr = {
        default = true,
        link = "FzfLuaPathColNr",
      },
      XuePickerCount = {
        default = true,
        link = "FzfLuaFzfInfo",
      },
      XuePickerDiagnosticCode = {
        default = true,
        link = "Comment",
      },
      XuePickerDiagnosticError = {
        default = true,
        link = "DiagnosticSignError",
      },
      XuePickerDiagnosticHint = {
        default = true,
        link = "DiagnosticSignHint",
      },
      XuePickerDiagnosticInfo = {
        default = true,
        link = "DiagnosticSignInfo",
      },
      XuePickerDiagnosticWarn = {
        default = true,
        link = "DiagnosticSignWarn",
      },
      XuePickerDirectory = {
        default = true,
        link = "FzfLuaDirPart",
      },
      XuePickerError = {
        default = true,
        link = "DiagnosticError",
      },
      XuePickerFilename = {
        default = true,
        link = "FzfLuaFilePart",
      },
      XuePickerGit = {
        default = true,
        link = "DiffChange",
      },
      XuePickerGrepPath = {
        default = true,
        link = "FzfLuaFilePart",
      },
      XuePickerGroup = {
        default = true,
        link = "FzfLuaHeaderText",
      },
      XuePickerGutter = {
        default = true,
        fg = "bg",
      },
      XuePickerHint = {
        default = true,
        link = "FzfLuaHeaderText",
      },
      XuePickerHintBind = {
        default = true,
        link = "FzfLuaHeaderBind",
      },
      XuePickerHintSeparator = {
        default = true,
        link = "FzfLuaFzfHeader",
      },
      XuePickerIcon = {
        default = true,
        link = "FzfLuaNormal",
      },
      XuePickerLineNr = {
        default = true,
        link = "FzfLuaPathLineNr",
      },
      XuePickerLivePrompt = {
        default = true,
        link = "FzfLuaLivePrompt",
      },
      XuePickerMarker = {
        default = true,
        link = "FzfLuaFzfMarker",
      },
      XuePickerMatch = {
        default = true,
        link = "FzfLuaFzfMatch",
      },
      XuePickerNormal = {
        default = true,
        link = "FzfLuaNormal",
      },
      XuePickerPointer = {
        default = true,
        link = "FzfLuaFzfPointer",
      },
      XuePickerPreviewLine = {
        default = true,
        link = "FzfLuaCursorLine",
      },
      XuePickerPrompt = {
        default = true,
        link = "FzfLuaFzfPrompt",
      },
      XuePickerQuery = {
        default = true,
        link = "FzfLuaFzfQuery",
      },
      XuePickerSelected = {
        default = true,
        link = "FzfLuaFzfCursorLine",
      },
      XuePickerStrong = {
        bold = true,
        default = true,
      },
    },
    hint = true,
    icons = "auto",
    keymaps = {
      accept = { "<CR>", "<C-y>" },
      close = { "<Esc>", "<C-c>" },
      delete = { "<C-d>" },
      next = { "<C-n>", "<Down>", "<Tab>" },
      preview = { "<C-o>" },
      previous = { "<C-p>", "<Up>", "<S-Tab>" },
      refresh = { "<C-r>" },
      split = { "<C-s>" },
      tab = { "<C-t>" },
      toggle = { "<C-x>" },
      toggle_all = { "<C-a>" },
      vsplit = { "<C-v>" },
    },
    layout = {
      height = 0.4,
      max_height = 18,
      min_preview = 6,
      preview_width = 0.5,
      wide = 100,
    },
    marker = "┃",
    matcher = {
      cwd_bonus = true,
      filename_bonus = true,
      frecency = false,
      fuzzy = true,
      history_bonus = false,
      ignorecase = true,
      smartcase = true,
    },
    path_format = "filename_first",
    performance = {
      cache_dirs = 3,
      cache_entries = 200000,
      render_ms = 16,
      slice_ms = 4,
    },
    pointer = "▌",
    preview = {
      debounce_ms = 60,
      enabled = false,
      max_bytes = 1048576,
      max_lines = 2000,
    },
    prompt = "> ",
    scan = {
      args = {},
      cmd = "rg",
      follow = false,
      globs = {},
      hidden = true,
      ignore = true,
    },
    sort = true,
    statusline = true,
  },
  pickers = {
    buffers = {
      filename_only = false,
      force = false,
      git = {
        enabled = false,
      },
      ignore_current_buffer = false,
      path_format = "relative",
      prompt = "Buffers> ",
      show_unlisted = false,
      show_unloaded = true,
      sort = false,
      sort_lastused = true,
    },
    diagnostics = {
      color_headings = true,
      color_icons = true,
      diag_code = true,
      diag_icons = true,
      diag_source = true,
      git = {
        enabled = false,
      },
      icons = false,
      multiline = 2,
      prompt = "Diagnostics> ",
      scope = "workspace",
      signs = {},
      sort = true,
    },
    files = {
      cwd_prompt = true,
      cwd_prompt_shorten_len = 32,
      cwd_prompt_shorten_val = 1,
      prompt = "Files> ",
    },
    git_files = {
      prompt = "GitFiles> ",
    },
    history = {
      prompt = "Command history> ",
      sort = false,
      type = "cmd",
    },
    live_grep = {
      backend = "auto",
      debounce_ms = 80,
      fallback = true,
      fff = {
        idle_timeout_ms = 60000,
        page_size = 256,
        ready_timeout_ms = 150,
        request_timeout_ms = 1000,
        time_budget_ms = 8,
      },
      globs = {},
      max_file_size = 10485760,
      max_results = 20000,
      mode = "regex",
      prompt = "Grep> ",
      ripgrep = {
        args = {},
        cmd = "rg",
      },
      smartcase = true,
      sort = false,
    },
    manpages = {
      prompt = "Man> ",
    },
    marks = {
      prompt = "Marks> ",
      sort = false,
    },
    oldfiles = {
      prompt = "Oldfiles> ",
      sort = false,
    },
    smart = {
      cwd_prompt = true,
      cwd_prompt_shorten_len = 32,
      cwd_prompt_shorten_val = 1,
      filter = {
        cwd = true,
      },
      matcher = {
        frecency = true,
      },
      prompt = "Files> ",
    },
    ui_input = {
      prompt = "Input> ",
    },
    ui_select = {
      prompt = "Select one of> ",
    },
  },
  ui = {
    input = false,
    select = false,
  },
})
