-- Generated by make defaults. Omit setup() to use these built-in defaults.
require("xue-picker").setup({
  defaults = {
    actions = {},
    filter = {
      cwd = false,
    },
    frecency = {
      half_life = 2592000,
      max_size = 10000,
      save_delay_ms = 1000,
    },
    git = {
      enabled = true,
      modified_bonus = false,
    },
    highlights = {
      XuePickerBorder = {
        default = true,
        link = "FzfLuaBorder",
      },
      XuePickerColNr = {
        default = true,
        link = "FzfLuaPathColNr",
      },
      XuePickerCount = {
        default = true,
        link = "FzfLuaFzfInfo",
      },
      XuePickerDirectory = {
        default = true,
        link = "FzfLuaDirPart",
      },
      XuePickerError = {
        default = true,
        link = "DiagnosticError",
      },
      XuePickerFilename = {
        default = true,
        link = "FzfLuaFilePart",
      },
      XuePickerGit = {
        default = true,
        link = "DiffChange",
      },
      XuePickerGroup = {
        default = true,
        link = "FzfLuaHeaderText",
      },
      XuePickerHint = {
        default = true,
        link = "FzfLuaFzfHeader",
      },
      XuePickerIcon = {
        default = true,
        link = "FzfLuaNormal",
      },
      XuePickerLineNr = {
        default = true,
        link = "FzfLuaPathLineNr",
      },
      XuePickerMarker = {
        default = true,
        link = "FzfLuaFzfMarker",
      },
      XuePickerMatch = {
        default = true,
        link = "FzfLuaFzfMatch",
      },
      XuePickerNormal = {
        default = true,
        link = "FzfLuaNormal",
      },
      XuePickerPreviewLine = {
        default = true,
        link = "FzfLuaCursorLine",
      },
      XuePickerPrompt = {
        default = true,
        link = "FzfLuaFzfPrompt",
      },
      XuePickerSelected = {
        default = true,
        link = "FzfLuaFzfCursorLine",
      },
    },
    icons = "auto",
    keymaps = {
      accept = { "<CR>", "<C-y>" },
      close = { "<Esc>", "<C-c>" },
      delete = { "<C-d>" },
      next = { "<C-n>", "<Down>", "<Tab>" },
      preview = { "<C-o>" },
      previous = { "<C-p>", "<Up>", "<S-Tab>" },
      refresh = { "<C-r>" },
      split = { "<C-s>" },
      tab = { "<C-t>" },
      toggle = { "<C-x>" },
      toggle_all = { "<C-a>" },
      vsplit = { "<C-v>" },
    },
    layout = {
      height = 0.4,
      max_height = 18,
      min_preview = 6,
      preview_width = 0.5,
      wide = 100,
    },
    marker = "●",
    matcher = {
      cwd_bonus = true,
      filename_bonus = true,
      frecency = false,
      fuzzy = true,
      history_bonus = false,
      ignorecase = true,
      smartcase = true,
    },
    path_format = "filename_first",
    performance = {
      cache_dirs = 3,
      cache_entries = 200000,
      render_ms = 16,
      slice_ms = 4,
    },
    pointer = "▸",
    preview = {
      debounce_ms = 60,
      enabled = false,
      max_bytes = 1048576,
      max_lines = 2000,
    },
    prompt = "❯ ",
    scan = {
      args = {},
      cmd = "rg",
      follow = false,
      globs = {},
      hidden = true,
      ignore = true,
    },
    sort = true,
  },
  pickers = {
    buffers = {
      force = false,
      sort = false,
    },
    diagnostics = {
      scope = "workspace",
      sort = false,
    },
    history = {
      sort = false,
      type = "cmd",
    },
    live_grep = {
      backend = "auto",
      debounce_ms = 80,
      fallback = true,
      fff = {
        idle_timeout_ms = 60000,
        page_size = 256,
        ready_timeout_ms = 150,
        request_timeout_ms = 1000,
        time_budget_ms = 8,
      },
      globs = {},
      max_file_size = 10485760,
      max_results = 20000,
      mode = "regex",
      ripgrep = {
        args = {},
        cmd = "rg",
      },
      smartcase = true,
      sort = false,
    },
    marks = {
      sort = false,
    },
    oldfiles = {
      sort = false,
    },
    smart = {
      filter = {
        cwd = true,
      },
      matcher = {
        frecency = true,
      },
    },
  },
  ui = {
    input = false,
    select = false,
  },
})
