vim.opt.runtimepath:prepend(vim.fn.getcwd())
local config = require("xue-picker.config")
local text = "-- Generated by make defaults. Omit setup() to use these built-in defaults.\n"
  .. 'require("xue-picker").setup('
  .. vim.inspect({
    defaults = config.defaults,
    pickers = config.pickers,
    ui = { select = false, input = false },
  })
  .. ")\n"
vim.fn.mkdir("doc", "p")
vim.fn.writefile(vim.split(text, "\n", { plain = true }), "doc/default-config.lua")
